-- -*-mode:lua;coding:utf-8 -*-
file = "lua"
project = "example"
title = "example documentation"
-- package = ""
all = true
-- format ='markdown | discount | lunamark | plain | backticks'
-- output = ""
-- dir = ""
boilerplate = true
-- ext = ""
-- one = true
-- style = ""
-- template = ""
-- merge = true


description = "openresty develop framework documentation"
-- examples = ""
-- readme = ""
-- pretty = "lxsh"
-- prettify_files = "show"
-- sort = true
